-- ═══════════════════════════════════════════
-- TopDeck Database Schema - PostgreSQL
-- ═══════════════════════════════════════════

CREATE TABLE categoria(
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    nombre VARCHAR(255)
);

CREATE TABLE tag(
    id_tag BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    nombre VARCHAR(255) UNIQUE,
    nombre_normalizado VARCHAR(255) UNIQUE,
    img_url VARCHAR(255)
);

CREATE TABLE producto(
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_categoria BIGINT,
    id_tag BIGINT,
    nombre VARCHAR(255),
    descripcion TEXT,
    precio DOUBLE PRECISION,
    stock INT,
    img_url VARCHAR(255),
    descuento INT DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    tipo_producto VARCHAR(20) NOT NULL DEFAULT 'PRODUCTO',
    FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria),
    FOREIGN KEY (id_tag) REFERENCES tag(id_tag),
    CHECK (tipo_producto IN ('PRODUCTO', 'SINGLE'))
);

CREATE TABLE producto_singles(
    id_producto_singles BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_producto BIGINT NOT NULL UNIQUE,
    atributos JSONB NOT NULL DEFAULT '{}',
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE
);

CREATE TABLE usuario(
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    nombre VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    telefono VARCHAR(255) UNIQUE,
    rol VARCHAR(20) CHECK (rol IN ('ADMIN', 'USER', 'GUEST')),
    ip_usuario VARCHAR(255),
    version_terminos_y_condiciones_aceptadas VARCHAR(255),
    terminos_aceptados BOOLEAN,
    fecha_aceptacion_terminos TIMESTAMP
);

CREATE TABLE direccion(
    id_direccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_usuario BIGINT NOT NULL,
    ciudad VARCHAR(255),
    provincia VARCHAR(255),
    codigo_postal VARCHAR(255),
    altura VARCHAR(255),
    pais VARCHAR(255),
    direccion VARCHAR(255),
    piso VARCHAR(255),
    principal BOOLEAN,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE pedido(
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_usuario BIGINT NOT NULL,
    id_direccion BIGINT,
    fecha_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'RECHAZADO')),
    total DOUBLE PRECISION NOT NULL,
    ip_usuario VARCHAR(255),
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    FOREIGN KEY (id_direccion) REFERENCES direccion(id_direccion)
);

CREATE TABLE detallepedido(
    id_detalle_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_pedido BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INT,
    precio_unitario DOUBLE PRECISION,
    subtotal DOUBLE PRECISION,
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE carrito (
    id_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_usuario BIGINT,
    session_id VARCHAR(255),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE detallecarrito(
    id_detalle_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    id_carrito BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INT DEFAULT 1,
    FOREIGN KEY (id_carrito) REFERENCES carrito(id_carrito),
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE auditoria(
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(255),
    fecha_audit TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    accion VARCHAR(255),
    tabla VARCHAR(255)
);

CREATE TABLE evento(
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    nombre_evento VARCHAR(255),
    ubicacion VARCHAR(255),
    fecha DATE,
    hora TIME,
    precio_entrada DOUBLE PRECISION,
    estado VARCHAR(20) CHECK (estado IN ('PROXIMAMENTE', 'EN_CURSO', 'FINALIZADO'))
);

-- ═══════════════════════════════════════════
-- Seed Data
-- ═══════════════════════════════════════════

INSERT INTO categoria(nombre) VALUES
    ('Sobres'),
    ('Cajas'),
    ('Barajas'),
    ('Accesorios'),
    ('Figuras');

INSERT INTO tag(nombre, img_url) VALUES
    ('Pokémon', 'https://placehold.co/600x600?text=Pokemon'),
    ('Dragon Ball Super', 'https://placehold.co/600x600?text=Dragon+Ball'),
    ('One Piece', 'https://placehold.co/600x600?text=One+Piece'),
    ('Yu-Gi-Oh!', 'https://placehold.co/600x600?text=Yu-Gi-Oh'),
    ('Magic: The Gathering', 'https://placehold.co/600x600?text=Magic');

UPDATE tag SET nombre_normalizado = replace(replace(replace(replace(replace(replace(replace(replace(
    lower(nombre),
    'á','a'),'é','e'),'í','i'),'ó','o'),'ú','u'),'ü','u'),'ñ','n'),'-','')
WHERE nombre_normalizado IS NULL;

INSERT INTO producto(
    id_categoria, id_tag, nombre, descripcion, precio, stock, img_url, descuento
) VALUES
    (1, 1, 'Sobre Evoluciones Prismáticas Pokémon',
     'Sobre de 10 cartas de la colección Evoluciones Prismáticas',
     8500.00, 50, 'https://placehold.co/600x600?text=Sobre+Pokemon', 0),
    (2, 1, 'Caja Evoluciones Prismáticas Pokémon',
     'Caja sellada de 36 sobres de Evoluciones Prismáticas',
     45000.00, 10, 'https://placehold.co/600x600?text=Caja+Pokemon', 5),
    (3, 1, 'Baraja Liga Evoluciones Prismáticas',
     'Baraja lista para jugar de la temporada Evoluciones Prismáticas',
     12000.00, 20, 'https://placehold.co/600x600?text=Baraja+Pokemon', 0),
    (1, 2, 'Sobre Battle Spirits Saga Dragon Ball',
     'Sobre de 12 cartas de Battle Spirits Saga Dragon Ball',
     6500.00, 40, 'https://placehold.co/600x600?text=Sobre+Dragon+Ball', 0),
    (2, 2, 'Caja Battle Spirits Saga Dragon Ball',
     'Caja sellada de 24 sobres de Battle Spirits Saga',
     35000.00, 8, 'https://placehold.co/600x600?text=Caja+Dragon+Ball', 10),
    (1, 3, 'Sobre Romance Dawn One Piece',
     'Sobre de 12 cartas de la colección Romance Dawn',
     7500.00, 30, 'https://placehold.co/600x600?text=Sobre+One+Piece', 0),
    (2, 3, 'Caja Romance Dawn One Piece',
     'Caja sellada de 24 sobres de Romance Dawn',
     40000.00, 5, 'https://placehold.co/600x600?text=Caja+One+Piece', 0),
    (1, 4, 'Sobre Rage of the Abyss Yu-Gi-Oh!',
     'Sobre de 9 cartas de Rage of the Abyss',
     5500.00, 60, 'https://placehold.co/600x600?text=Yu-Gi-Oh', 0),
    (1, 5, 'Sobre Innistrad Remastered Magic',
     'Sobre de 15 cartas de Innistrad Remastered',
     9000.00, 25, 'https://placehold.co/600x600?text=Magic', 0),
    (4, 1, 'Album Pokémon 9 Bolsillos',
     'Álbum de colección con fundas para 9 cartas por página',
     3500.00, 100, 'https://placehold.co/600x600?text=Album+Pokemon', 0);

-- ═══════════════════════════════════════════
-- Usuario administrador por defecto
-- ═══════════════════════════════════════════

INSERT INTO usuario (nombre, email, password, rol, terminos_aceptados) VALUES
    ('orick', 'odnr2004@gmail.com', '$2a$10$59LK7r4kI/igkLH1.anN.OSx5T6DjHiCKw87GeOmx4W8/Ow6D.KK6', 'ADMIN', TRUE);

-- ═══════════════════════════════════════════
-- Indices para optimizar queries del dashboard
-- ═══════════════════════════════════════════

CREATE INDEX idx_pedido_estado ON pedido(estado);
CREATE INDEX idx_detalle_pedido_producto ON detallepedido(id_pedido, id_producto);
CREATE INDEX idx_producto_activo_stock ON producto(activo, stock);
CREATE INDEX idx_producto_activo_descuento ON producto(activo, descuento);
CREATE INDEX idx_auditoria_accion ON auditoria(accion);
CREATE INDEX idx_evento_estado ON evento(estado);

-- Indices para producto_singles (JSONB)
CREATE INDEX idx_producto_tipo ON producto(tipo_producto);
CREATE INDEX idx_producto_tipo_activo ON producto(tipo_producto, activo);
CREATE INDEX idx_singles_atributos ON producto_singles USING GIN(atributos);
CREATE INDEX idx_singles_rareza ON producto_singles((atributos->>'rareza'));
CREATE INDEX idx_singles_set ON producto_singles((atributos->>'set'));
