spring.application.name=TopDeckAPI
spring.datasource.url=jdbc:mysql://localhost:3306/topdeck_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=0994902023

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=8xJ9kL2mN4pQ6ry8tUvWx2zAbCdEfDhIjKlMnOpdrStUvWSYzAbCdEfGhIjKlM3OpQr

